- hosts: app
  remote_user: root

  # installing nginx
  tasks:
    - name: update the sources list
      shell: sudo apt-get update -y

    - name: upgrade any packages available
      shell: sudo apt-get upgrade -y

    - name: install nginx
      shell: sudo apt-get install nginx -y

    - name: install git
      shell: sudo apt-get install git -y

    # - name: install python
    #   shell: sudo apt-get install python-software-properties

    - name: install nodejs
      shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

    - name: install nodejs
      shell: sudo apt-get install nodejs -y

    - name: enter app directory
      shell: cd /home/ubuntu/app

    - name: installing ejs, mongoose and express
      shell: sudo npm install ejs mongoose express

    - name: populating posts page
      shell: node seeds/seed.js

    - name: removing default
      shell: sudo rm /etc/nginx/sites-enabled/default

    - name: replacing default
      shell: sudo ln -s /home/ubuntu/environment/default /etc/nginx/sites-enabled/default

    - name: stopping nginx
      shell: sudo systemctl stop nginx

    - name: starting nginx
      shell: sudo systemctl start nginx

    - name: nginx
      shell: sudo nginx -t
